import os,sys,time
import math
os.system ('clear')

print("Local: "+strftime("%a, %d %b %Y %I:%M:%S %p %Z\n"))
print ("-----------------------------------------------------------------------")
print ("1).Converter Temperature")
print ("2).Test Network Speed")
print ("3).Two Dimentional Figure")
print ("4).Volume ")
print ("-----------------------------------------------------------------------")
menu = input("Choose Menu : ")
print ("-----------------------------------------------------------------------")

if menu == '1':
  print ("Choose Menu : ")
  print ("1). Celcius")
  print ("2). Fahrenheit")
  print ("3). Reamur")
  print ("4). Kelvin")
  choose = int(input("Input Menu : "))
  print ("-----------------------------------------------------------------------")
  if choose == '1':
    os.system ('clear')
    print ("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    print ("1).Celcius To Farenheit")
    print ("2).Celcius To Reamur")
    print ("3).Celcius To Kelvin")
    print ("-----------------------------------------------------------------------")
    
    choose1 = input("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    input_suhu = float(input("Temperature Input : "))
    print ("-----------------------------------------------------------------------")
    
    if choose1 == '1':
      ac1 = float(9 / 5 * input_suhu + 32)
      print ("-----------------------------------------------------------------------")
      print ("Results = " ,ac1, "°F")
      print ("-----------------------------------------------------------------------")
    elif choose1 == '2':
      ac2 = float(4 / 5 * input_suhu)
      print ("-----------------------------------------------------------------------")
      print ("Results = " ,ac2, "°Re")
      print ("-----------------------------------------------------------------------")
    elif choose1 == '3':
      ac3 = float(input_suhu + 273.15)
      print ("-----------------------------------------------------------------------")
      print ("Results = " ,ac3, "°K")
      print ("-----------------------------------------------------------------------")
    else:
      print ("Invalid Input")
      
  if choose == '2':
    os.system ('clear')
    print ("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    print ("1).Farenheit To Celcius")
    print ("2).Farenheit To Reamur")
    print ("3).Farenheit To Kelvin")
    print ("-----------------------------------------------------------------------")
    
    choose2 = input("Choose Menu : ")
    input_suhu = float(input("Temperature Input : "))
    
    if choose2 == '1':
      af1 = float(5 / 9 * (input_suhu - 32))
      print ("-----------------------------------------------------------------------")
      print ("Results = ",af1,"°C")
      print ("-----------------------------------------------------------------------")
    elif choose2 == '2':
      af2 = float(4 / 9 * (input_suhu - 32))
      print ("-----------------------------------------------------------------------")
      print ("Results = ",af2,"°Re")
      print ("-----------------------------------------------------------------------")
    elif choose2 == '3':
      af3 = float((input_suhu - 32) * 5 / 9 + 273.15)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",af3,"°K")
      print ("-----------------------------------------------------------------------")
    else:
      print ("Invalid Input")
  if choose == '3':
    os.system ('clear')
    print ("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    print ("1).Reamur To Celcius")
    print ("2).Reamur To Farenheit")
    print ("3).Reamur To Kelvin")
    print ("-----------------------------------------------------------------------")
    choose3 = input("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    input_suhu = float(input("Temperature Input : "))
    if choose3 == '1':
      ar1 = float(5 / 4 * input_suhu)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ar1,"°C")
      print ("-----------------------------------------------------------------------")
    elif choose3 == '2':
      ar2 = float(9 / 4 * input_suhu + 32)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ar2,"°F")
      print ("-----------------------------------------------------------------------")
    elif choose3 == '3':
      ar3 = float(5 / 4 * input_suhu + 273.15)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ar3,"°K")
      print ("-----------------------------------------------------------------------")
    else:
      print ("Invalid Input")
  if choose == '4':
    os.system ('clear')
    print ("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    print ("1).Kelvin To Celcius")
    print ("2).Kelvin To Farenheit")
    print ("3).Kelvin To Reamur")
    print ("-----------------------------------------------------------------------")
    
    choose4 = input("Choose Menu : ")
    print ("-----------------------------------------------------------------------")
    input_suhu = float(input("Temperature Input : "))
    
    if choose4 == '1':
      ak1 = float(input_suhu - 273.15)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ak1,"°C")
      print ("-----------------------------------------------------------------------")
    elif choose4 == '2':
      ak2 = float((input_suhu - 273.15) * 9/5 + 32)
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ak2,"°F")
      print ("-----------------------------------------------------------------------")
    elif choose4 == '3':
      ak3 = float(4 / 5 * (input_suhu - 273))
      print ("-----------------------------------------------------------------------")
      print ("Results = ",ak3,"°Re")
      print ("-----------------------------------------------------------------------")
    else:
      print ("Invalid Input")
elif menu == '2':
  print ("Information Network")
  print ("-----------------------------------------------------------------------")
  os.system('ping 8.8.8.8')
elif menu == '3':
  os.system('clear')
  
  print ("Pilih Menu :")
  print ("-----------------------------------------------------------------------")
  print ("1).Lingkaran")
  print ("2).Persegi")
  print ("3).Persegi Panjang")
  print ("4).Trapesium Sama Kaki")
  print ("5).Jajar Genjang")
  print ("6).Segitiga")
  print ("7).Layang - Layang")
  print ("8).Belah Ketupat")
  print ("-----------------------------------------------------------------------")
  
  datar = input("Masukkan Input : ")
  print ("-----------------------------------------------------------------------")
  if datar == '1':
    
    print ("Pilih Menu Lingkaran : ")
    print ("-----------------------------------------------------------------------")
    print ("1). L = π × r2 ")
    print ("2). L = π × d ")
    print ("3). d = r × 2 ")
    print ("4). r = ½ × d ")
    print ("5). K = 2 × π × r ")
    print ("-----------------------------------------------------------------------")
    inp_o = input("Masukkan Input : ")
    print ("-----------------------------------------------------------------------")
    
    if inp_o == '1':
      print ("Luas Lingkaran Dari Jari - Jari (cm) ")
      print ("-----------------------------------------------------------------------")
      inp_r1 = float(input("Masukan Jari - Jari (cm) : "))
      calc_r1 = float(22 / 7 * inp_r1 ** 2)
      print ("Results = ",calc_r1," cm")
    elif inp_o == '2':
      print ("Luas Lingkaran Dari Diameter (cm) ")
      print ("-----------------------------------------------------------------------")
      inp_r2 = float(input("Masukan Diameter (cm) : "))
      calc_r2 = float(22 / 7 * inp_r2)
      print ("Results = ",calc_r2," cm")
    elif inp_o == '3':
      print ("Diameter Lingkaran (cm) ")
      print ("-----------------------------------------------------------------------")
      inp_r3 = float(input("Masukan Jari - Jari (cm) : "))
      calc_r3 = float(inp_r3 * 2)
      print ("Results = ",calc_r3," cm")
    elif inp_o == '4':
      print ("Jari - Jari Lingkaran (cm) ")
      print ("-----------------------------------------------------------------------")
      inp_r4 = float(input("Masukan Diameter (cm) : "))
      calc_r4 = float(inp_r4 / 2)
      print ("Results = ",calc_r4," cm")
    elif inp_o == '5':
      print ("Keliling Lingkaran (cm) ")
      print ("-----------------------------------------------------------------------")
      inp_r5 = float(input("Masukan Jari - Jari (cm) : "))
      calc_r5 = float(2 * 22 / 7 * inp_r5)
      print ("Results = ",calc_r5," cm")
    else:
      print ("Input Salah !")
  elif datar == '2':
    print ("Keterangan : ")
    print ("-----------------------------------------------------------------------")
    print (" L = Luas Persegi")
    print (" K = Keliling Persegi ")
    print (" s = Sisi Persegi")
    print ("-----------------------------------------------------------------------")
    print ("1).Cari (L) Persegi")
    print ("2).Cari (K) Persegi")
    print ("3).Cari (s) Persegi")
    print ("-----------------------------------------------------------------------")

    inp_p = input("Pilih Menu : ")
    if inp_p == '1':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI LUAS PERSEGI")
      print ("-----------------------------------------------------------------------")
      inp_p1 = float(input("Masukkan Sisi (cm) : "))
      calc_p1 = float(inp_p1 ** 2)
      print ("Results = ",calc_p1," cm")
    elif inp_p == '2':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI KELILING PERSEGI")
      print ("-----------------------------------------------------------------------")
      print ("1).Cari (K) Dari (L)")
      print ("2).Cari (K) Dari (s)")
      inp_k_p = input("Pilih Menu : ")
      if inp_k_p == '1':
        print ("-----------------------------------------------------------------------")
        inp_L_p = float(input("Masukkan Luas Persegi (cm) : "))
        print ("-----------------------------------------------------------------------")
        pro_inp_L_p = math.sqrt(inp_L_p)
        pro_inp_L_p_2 = float(pro_inp_L_p * 4)
        print ("Results = ",pro_inp_L_p_2," cm")
        print ("-----------------------------------------------------------------------")
      elif inp_k_p == '2':
        print ("-----------------------------------------------------------------------")
        inp_p2 = float(input("Masukkan Sisi (cm) : "))
        calc_p2 = float(inp_p2 * 4)
        print ("Results = ",calc_p2," cm")
      else:
        print ("Input Salah !")
    elif inp_p == '3':
      print ("MENCARI SISI PERSEGI")
      print ("-----------------------------------------------------------------------")
      inp_p3 = float(input("Masukkan Keliling (cm) : "))
      calc_p3 = float(inp_p3 / 4)
      print ("Results = ",calc_p3," cm")
    else:
        print ("Input Salah !")
        
  elif datar == '3':
    print ("Keterangan : ")
    print ("-----------------------------------------------------------------------")
    print (" L = Luas Persegi Panjang ")
    print (" K = Keliling Persegi Panjang ")
    print (" p = Panjang Persegi Panjang")
    print (" l = Lebar Persegi Panjang ")
    print ("-----------------------------------------------------------------------")
    print ("1).Cari (L) Persegi Panjang")
    print ("2).Cari (K) Persegi Panjang")
    print ("3).Cari (p) Persegi Panjang")
    print ("4).Cari (l) Persegi Panjang")
    print ("-----------------------------------------------------------------------")
    inp_pp = input("Pilih Menu : ")
    if inp_pp == '1':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI LUAS PERSEGI PANJANG")
      print ("-----------------------------------------------------------------------")
      inp_pp1 = float(input("Masukkan Lebar (cm) : "))
      inp_pp12 = float(input("Masukkan Panjang (cm) : "))
      calc_p12 = float(inp_pp1 * inp_pp12)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",calc_p12," cm")
    elif inp_pp == '2':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI KELILING PERSEGI PANJANG")
      print ("-----------------------------------------------------------------------")
      inp_pp2 = float(input("Masukkan Lebar (cm) : "))
      inp_pp22 = float(input("Masukkan Panjang (cm) : "))
      calc_22 = float(2 * (inp_pp2 + inp_pp22))
      print ("-----------------------------------------------------------------------")
      print ("Results : ",calc_22," cm")
    elif inp_pp == '3':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI PANJANG PERSEGI PANJANG")
      print ("-----------------------------------------------------------------------")
      inp_pp3 = float(input("Masukkan Luas (cm) : "))
      inp_pp33 = float(input("Masukkan Lebar (cm) : "))
      calc_33 = float(inp_pp3 / inp_pp33)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",calc_33," cm")
    elif inp_pp == '4':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI LEBAR PERSEGI PANJANG")
      print ("-----------------------------------------------------------------------")
      inp_pp4 = float(input("Masukkan Luas (cm) : "))
      inp_pp44 = float(input("Masukkan Panjang (cm) : "))
      calc_44 = float(inp_pp4 / inp_pp44)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",calc_44," cm")
    else:
      print ("Input Salah !")
  if datar == '4':
    print ("Keterangan : ")
    print ("-----------------------------------------------------------------------")
    print (" L = Luas Trapesium ")
    print (" K = Keliling trapesium ")
    print (" a = alas/sisi bawah trapesium ")
    print (" b = atap/sisi atas trapesium ")
    print (" c = sisi miring kiri trapesium ")
    print (" d = sisi miring kanan trapesium ")
    print (" t = tinggi trapesium ")
    print ("-----------------------------------------------------------------------")
    print ("1).Cari (L) Trapesium (cm) ")
    print ("2).Cari (K) Trapesium (cm) ")
    print ("3).Cari (a) Trapesium (cm) ")
    print ("4).Cari (b) Trapesium (cm) ")
    print ("5).Cari (t) Trapesium (cm) ")
    print ("-----------------------------------------------------------------------")
    inp_data4 = input("Pilih Menu : ")
    if inp_data4 == '1':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI LUAS TRAPESIUM")
      print ("-----------------------------------------------------------------------")
      data_4_11 = float(input("Masukkan a (cm) : "))
      data_4_12 = float(input("Masukkan b (cm) : "))
      data_4_13 = float(input("Masukkan t (cm) : "))
      pro_41 = float(1 / 2 * data_4_13 * (data_4_11 + data_4_12))
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_41," cm")
    elif inp_data4 == '2':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI KELILING TRAPESIUM")
      print ("-----------------------------------------------------------------------")
      print ("1).Cari (K) Dari (a,b,t)")
      print ("2).Cari (K) Dari (a,b,c,d)")
      print ("-----------------------------------------------------------------------")
      select_data_42 = input("Pilih Menu : ")
      if select_data_42 == '1':
        print ("-----------------------------------------------------------------------")
        data_42_1 = float(input("Masukkan a (cm) : "))
        data_42_2 = float(input("Masukkan b (cm) : "))
        data_42_3 = float(input("Masukkan t (cm) : "))
        alas_pyth = float((data_42_1 - data_42_2) / 2)
        pro_42_4_2 = float((data_42_3 ** 2) + (alas_pyth **2))
        prolast1 = math.sqrt(pro_42_4_2)
        last1 = (data_42_1 + data_42_2 + (prolast1 * 2))
        print ("-----------------------------------------------------------------------")
        print ("Results : ",last1," cm")
      elif select_data_42 == '2':
        print ("-----------------------------------------------------------------------")
        inp_a = float(input("Masukkan a (cm) : "))
        inp_b = float(input("Masukkan b (cm) : "))
        inp_c = float(input("Masukkan c (cm) : "))
        inp_d = float(input("Masukkan d (cm) : "))
        pro_select_data_42 = float(inp_a + inp_b + inp_c + inp_d)
        print ("Results : ",pro_select_data_42," cm")
      else:
        print ("Input Salah !")
    elif inp_data4 == '3':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI ALAS/SISI BAWAH TRAPESIUM")
      print ("-----------------------------------------------------------------------")
      inp_L = float(input("Masukkan Luas Trapesium (cm) : "))
      inp_t = float(input("Masukkan Tinggi Trapesium (cm) : "))
      inp_b1 = float(input("Masukkan Atap Trapesium (cm) ; "))
      pro_inp_data4_3 = float(2 * inp_L / inp_t - inp_b1)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_inp_data4_3," cm")
      print ("-----------------------------------------------------------------------")
    elif inp_data4 == '4':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI ATAP/SISI ATAS TRAPESIUM")
      print ("-----------------------------------------------------------------------")
      inp_L1 = float(input("Masukkan Luas Trapesium (cm) : "))
      inp_t1 = float(input("Masukkan Tinggi Trapesium (cm) : "))
      inp_b2 = float(input("Masukkan Alas Trapesium (cm) ; "))
      pro_inp_data4_4 = float(2 * inp_L1 / inp_t1 - inp_b2)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_inp_data4_4," cm")
      print ("-----------------------------------------------------------------------")
    elif inp_data4 == '5':
      print ("-----------------------------------------------------------------------")
      print ("MENCARI TINGGI TRAPESIUM")
      print ("-----------------------------------------------------------------------")
      inp_L3 = float(input("Masukkan Luas Trapesium (cm) : "))
      inp_b3 = float(input("Masukkan Alas Trapesium (cm) : "))
      inp_a3 = float(input("Masukkan Atap Trapesium (cm) ; "))
      pro_inp_data4_5= float(2 * inp_L3 / (inp_a3 + inp_b3))
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_inp_data4_5," cm")
      print ("-----------------------------------------------------------------------")
      #hereeeeeeee
if menu == '2':
  print ("1).KUBUS")
  print ("2).BALOK")
  print ("3.TABUNG")
  print ("4.PRISMA")
  print ("5).BOLA")
  print ("-----------------------------------------------------------------------")
  vol = float("Masukkan Input : ")
  print ("-----------------------------------------------------------------------")
  if vol == '1':
    print ("MENCARI VOLUME KUBUS")
    print ("-----------------------------------------------------------------------")
    inp_kb = float("Masukkan Sisi (cm) : ")
    pro_kb = float(inp_kb*inp_kb*inp_kb)
    print ("-----------------------------------------------------------------------")
    print ("Results : ",pro_kb," (cm)")
  if vol == '2':
    print ("MENCARI VOLUME BALOK")
    print ("-----------------------------------------------------------------------")
    inp_blk = float("Masukkan Panjang (cm) : ")
    inp2_blk = float("Masukkan Lebar (cm) : ")
    inp3_blk = float("Masukkan Tinggi (cm) : ")
    pro_blk = float(inp_blk*inp2_blk*inp3_blk)
    print ("-----------------------------------------------------------------------")
    print ("Results : ",pro_blk," (cm)")
    print ("-----------------------------------------------------------------------")
  if vol == '3':
    print ("MENCARI VOLUME KUBUS")
    print ("-----------------------------------------------------------------------")
    print ("Keterangan : ")
    print ("-----------------------------------------------------------------------")
    print (" L = Luas Lingkaran ")
    print (" r = Jari - Jari Lingkaran ")
    print (" d = Diameter Lingkaran ")
    print (" t = Tinggi Lingkaran ")
    print ("-----------------------------------------------------------------------")
    print ("1).CARI VOLUME TABUNG (L and t) ")
    print ("2).CARI VOLUME TABUNG (r and t) ")
    print ("3).CARI VOLUME TABUNG (d and t) ")
    print ("-----------------------------------------------------------------------")
    inp_m_tb = float("Masukkan Input : ")
    print ("-----------------------------------------------------------------------")
    if inp_m_tb == '1':
      print ("MENCARI VOLUME TABUNG")
      print ("-----------------------------------------------------------------------")
      inp_l_tb = float("Masukkan Luas (cm) : ")
      inp_t_tb = float("Masukkan tinggi (cm) : ")
      pro_lt_1 = float(inp_l_tb*inp_l_tb)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_lt_1," cm")
      print ("-----------------------------------------------------------------------")
    if inp_m_tb == '2':
      print ("MENCARI VOLUME TABUNG")
      print ("-----------------------------------------------------------------------")
      inp_r_tb = float("Masukkan Jari - Jari (cm) : ")
      inp_t2_tb = float("Masukkan tinggi (cm) : ")
      pro_lt_1 = float((22/7*inp_r_tb*inp_r_tb)*inp_t2_tb)
      print ("-----------------------------------------------------------------------")
      print ("Results : ",pro_rt2_tb," cm")
      print ("-----------------------------------------------------------------------")